//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
    using Diagnostics;

    public abstract unsafe partial class CefRenderHandler 
    {
#if DIAGNOSTICS
        internal static int ObjectCt;
#endif

        private static ObjectTable<CefRenderHandler> pointers = new ObjectTable<CefRenderHandler>();



        private int refct;
        private cef_render_handler_t* ptr;
        private bool disposed;

        private cef_base_t.add_ref_delegate bs_add_ref;
        private cef_base_t.release_delegate bs_release;
        private cef_base_t.get_refct_delegate bs_get_refct;
        private cef_render_handler_t.get_view_rect_delegate bs_get_view_rect;
        private cef_render_handler_t.get_screen_rect_delegate bs_get_screen_rect;
        private cef_render_handler_t.get_screen_point_delegate bs_get_screen_point;
        private cef_render_handler_t.on_popup_show_delegate bs_on_popup_show;
        private cef_render_handler_t.on_popup_size_delegate bs_on_popup_size;
        private cef_render_handler_t.on_paint_delegate bs_on_paint;
        private cef_render_handler_t.on_cursor_change_delegate bs_on_cursor_change;

        public CefRenderHandler()
        {
            this.refct = 0;
            this.ptr = cef_render_handler_t.Alloc();
#if DIAGNOSTICS
			Interlocked.Increment(ref ObjectCt);
#endif

#if DIAGNOSTICS
            Cef.Logger.Trace(LogTarget.CefRenderHandler, this.ptr, LogOperation.Create);
#endif

            this.bs_add_ref = new cef_base_t.add_ref_delegate(this.add_ref);
            this.ptr->@base.add_ref = Marshal.GetFunctionPointerForDelegate(this.bs_add_ref);

            this.bs_release = new cef_base_t.release_delegate(this.release);
            this.ptr->@base.release = Marshal.GetFunctionPointerForDelegate(this.bs_release);

            this.bs_get_refct = new cef_base_t.get_refct_delegate(this.get_refct);
            this.ptr->@base.get_refct = Marshal.GetFunctionPointerForDelegate(this.bs_get_refct);

            this.bs_get_view_rect = new cef_render_handler_t.get_view_rect_delegate(this.get_view_rect);
            this.ptr->get_view_rect = Marshal.GetFunctionPointerForDelegate(this.bs_get_view_rect);

            this.bs_get_screen_rect = new cef_render_handler_t.get_screen_rect_delegate(this.get_screen_rect);
            this.ptr->get_screen_rect = Marshal.GetFunctionPointerForDelegate(this.bs_get_screen_rect);

            this.bs_get_screen_point = new cef_render_handler_t.get_screen_point_delegate(this.get_screen_point);
            this.ptr->get_screen_point = Marshal.GetFunctionPointerForDelegate(this.bs_get_screen_point);

            this.bs_on_popup_show = new cef_render_handler_t.on_popup_show_delegate(this.on_popup_show);
            this.ptr->on_popup_show = Marshal.GetFunctionPointerForDelegate(this.bs_on_popup_show);

            this.bs_on_popup_size = new cef_render_handler_t.on_popup_size_delegate(this.on_popup_size);
            this.ptr->on_popup_size = Marshal.GetFunctionPointerForDelegate(this.bs_on_popup_size);

            this.bs_on_paint = new cef_render_handler_t.on_paint_delegate(this.on_paint);
            this.ptr->on_paint = Marshal.GetFunctionPointerForDelegate(this.bs_on_paint);

            this.bs_on_cursor_change = new cef_render_handler_t.on_cursor_change_delegate(this.on_cursor_change);
            this.ptr->on_cursor_change = Marshal.GetFunctionPointerForDelegate(this.bs_on_cursor_change);

        }

        ~CefRenderHandler()
        {
#if DIAGNOSTICS
            Cef.Logger.Trace(LogTarget.CefRenderHandler, this.ptr, "~CefRenderHandler");
#endif
			Dispose(false);
        }


		protected virtual void Dispose(bool disposing)
        {
#if DIAGNOSTICS
            Cef.Logger.Trace(LogTarget.CefRenderHandler, this.ptr, LogOperation.Dispose, "Disposing=[{0}]", disposing);
#endif

			this.disposed = true;

			if (this.ptr != null)
            {
#if DIAGNOSTICS
                Interlocked.Decrement(ref ObjectCt);
#endif
				cef_render_handler_t.Free(this.ptr);
                this.ptr = null;
			}

            if (disposing)
			{
			}
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object.
		/// It should be called for every new copy of a pointer to a given object.
		/// The resulting reference count value is returned and should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int AddRef()
        {
            var result = Interlocked.Increment(ref this.refct);
            #if DIAGNOSTICS
            Cef.Logger.Trace(LogTarget.CefRenderHandler, this.ptr, LogOperation.AddRef, "{0}", result);
            #endif
			if (result == 1)
			{
				pointers.Add((IntPtr)ptr, this);
			}
            return result;
        }

        /// <summary>
        /// The Release method decrements the reference count for the object.
		/// If the reference count on the object falls to 0, then the object should free itself from memory.
		/// The resulting reference count value is returned and should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef(bool disposing = true)
        {
            var result = Interlocked.Decrement(ref this.refct);
            #if DIAGNOSTICS
            Cef.Logger.Trace(LogTarget.CefRenderHandler, this.ptr, LogOperation.ReleaseRef, "{0}", result);
            #endif
			if (result == 0)
			{
                pointers.Remove((IntPtr)ptr);
			}
            return result;
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return this.refct; }
        }

        internal cef_render_handler_t* NativePointer
        {
            get { return this.ptr; }
        }

        internal cef_render_handler_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private int add_ref(cef_base_t* self)
        {
            ThrowIfObjectDisposed();
            return AddRef();
        }

        private int release(cef_base_t* self)
        {
            ThrowIfObjectDisposed();
            return ReleaseRef();
        }

        private int get_refct(cef_base_t* self)
        {
            ThrowIfObjectDisposed();
            return RefCount;
        }

        protected void ThrowIfObjectDisposed()
        {
            if (this.disposed) ThrowObjectDisposedException();
        }

        private static void ThrowObjectDisposedException()
        {
            throw new ObjectDisposedException("CefRenderHandler");
        }

		[Conditional("DEBUG")]
		private void CheckNativePointer()
		{
            if (this.ptr == null) ThrowObjectDisposedException();
		}
    }
}
