//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefDomEvent : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefDomEvent proxy from pointer.
        /// </summary>
        internal static CefDomEvent From(cef_domevent_t* ptr)
        {
            if (ptr == null) ThrowNullNativePointer();
			return new CefDomEvent(ptr);
        }
		
        internal static CefDomEvent FromOrDefault(cef_domevent_t* ptr)
        {
            if (ptr != null) return new CefDomEvent(ptr);
            else return null;
        }

        private static void ThrowNullNativePointer()
        {
            throw new NullReferenceException("CefDomEvent");
        }

        private cef_domevent_t* ptr;

        private CefDomEvent(cef_domevent_t* ptr)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefDomEvent, this.ptr, LogOperation.Create);
#endif

            // if (addRef) this.AddRef();
        }

        #region IDisposable
        ~CefDomEvent()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefDomEvent, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_domevent_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_domevent_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_domevent_t.get_type_delegate get_type
        {
            get
            {
                return (cef_domevent_t.get_type_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_type, typeof(cef_domevent_t.get_type_delegate));
            }
        }

        private cef_domevent_t.get_category_delegate get_category
        {
            get
            {
                return (cef_domevent_t.get_category_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_category, typeof(cef_domevent_t.get_category_delegate));
            }
        }

        private cef_domevent_t.get_phase_delegate get_phase
        {
            get
            {
                return (cef_domevent_t.get_phase_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_phase, typeof(cef_domevent_t.get_phase_delegate));
            }
        }

        private cef_domevent_t.can_bubble_delegate can_bubble
        {
            get
            {
                return (cef_domevent_t.can_bubble_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->can_bubble, typeof(cef_domevent_t.can_bubble_delegate));
            }
        }

        private cef_domevent_t.can_cancel_delegate can_cancel
        {
            get
            {
                return (cef_domevent_t.can_cancel_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->can_cancel, typeof(cef_domevent_t.can_cancel_delegate));
            }
        }

        private cef_domevent_t.get_document_delegate get_document
        {
            get
            {
                return (cef_domevent_t.get_document_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_document, typeof(cef_domevent_t.get_document_delegate));
            }
        }

        private cef_domevent_t.get_target_delegate get_target
        {
            get
            {
                return (cef_domevent_t.get_target_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_target, typeof(cef_domevent_t.get_target_delegate));
            }
        }

        private cef_domevent_t.get_current_target_delegate get_current_target
        {
            get
            {
                return (cef_domevent_t.get_current_target_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_current_target, typeof(cef_domevent_t.get_current_target_delegate));
            }
        }

    }
}
