//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefFrame : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefFrame proxy from pointer.
        /// </summary>
        internal static CefFrame From(cef_frame_t* ptr)
        {
			return new CefFrame(ptr, false);
        }

        /// <summary>
        /// Create CefFrame proxy from pointer and optionally increments the reference count for the object.
        /// </summary>
        internal static CefFrame Create(cef_frame_t* ptr, bool addRefCount)
        {
            return new CefFrame(ptr, addRefCount);
        }

        private cef_frame_t* ptr;

        private CefFrame(cef_frame_t* ptr, bool addRefCount)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefFrame, this.ptr, LogOperation.Create);
#endif

			if (addRefCount) this.AddRef();
        }

        #region IDisposable
        ~CefFrame()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefFrame, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_frame_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_frame_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_frame_t.undo_delegate undo
        {
            get
            {
                return (cef_frame_t.undo_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->undo, typeof(cef_frame_t.undo_delegate));
            }
        }

        private cef_frame_t.redo_delegate redo
        {
            get
            {
                return (cef_frame_t.redo_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->redo, typeof(cef_frame_t.redo_delegate));
            }
        }

        private cef_frame_t.cut_delegate cut
        {
            get
            {
                return (cef_frame_t.cut_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->cut, typeof(cef_frame_t.cut_delegate));
            }
        }

        private cef_frame_t.copy_delegate copy
        {
            get
            {
                return (cef_frame_t.copy_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->copy, typeof(cef_frame_t.copy_delegate));
            }
        }

        private cef_frame_t.paste_delegate paste
        {
            get
            {
                return (cef_frame_t.paste_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->paste, typeof(cef_frame_t.paste_delegate));
            }
        }

        private cef_frame_t.del_delegate del
        {
            get
            {
                return (cef_frame_t.del_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->del, typeof(cef_frame_t.del_delegate));
            }
        }

        private cef_frame_t.select_all_delegate select_all
        {
            get
            {
                return (cef_frame_t.select_all_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->select_all, typeof(cef_frame_t.select_all_delegate));
            }
        }

        private cef_frame_t.print_delegate print
        {
            get
            {
                return (cef_frame_t.print_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->print, typeof(cef_frame_t.print_delegate));
            }
        }

        private cef_frame_t.view_source_delegate view_source
        {
            get
            {
                return (cef_frame_t.view_source_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->view_source, typeof(cef_frame_t.view_source_delegate));
            }
        }

        private cef_frame_t.get_source_delegate get_source
        {
            get
            {
                return (cef_frame_t.get_source_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_source, typeof(cef_frame_t.get_source_delegate));
            }
        }

        private cef_frame_t.get_text_delegate get_text
        {
            get
            {
                return (cef_frame_t.get_text_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_text, typeof(cef_frame_t.get_text_delegate));
            }
        }

        private cef_frame_t.load_request_delegate load_request
        {
            get
            {
                return (cef_frame_t.load_request_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->load_request, typeof(cef_frame_t.load_request_delegate));
            }
        }

        private cef_frame_t.load_url_delegate load_url
        {
            get
            {
                return (cef_frame_t.load_url_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->load_url, typeof(cef_frame_t.load_url_delegate));
            }
        }

        private cef_frame_t.load_string_delegate load_string
        {
            get
            {
                return (cef_frame_t.load_string_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->load_string, typeof(cef_frame_t.load_string_delegate));
            }
        }

        private cef_frame_t.load_stream_delegate load_stream
        {
            get
            {
                return (cef_frame_t.load_stream_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->load_stream, typeof(cef_frame_t.load_stream_delegate));
            }
        }

        private cef_frame_t.execute_java_script_delegate execute_java_script
        {
            get
            {
                return (cef_frame_t.execute_java_script_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->execute_java_script, typeof(cef_frame_t.execute_java_script_delegate));
            }
        }

        private cef_frame_t.is_main_delegate is_main
        {
            get
            {
                return (cef_frame_t.is_main_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->is_main, typeof(cef_frame_t.is_main_delegate));
            }
        }

        private cef_frame_t.is_focused_delegate is_focused
        {
            get
            {
                return (cef_frame_t.is_focused_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->is_focused, typeof(cef_frame_t.is_focused_delegate));
            }
        }

        private cef_frame_t.get_name_delegate get_name
        {
            get
            {
                return (cef_frame_t.get_name_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_name, typeof(cef_frame_t.get_name_delegate));
            }
        }

        private cef_frame_t.get_url_delegate get_url
        {
            get
            {
                return (cef_frame_t.get_url_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_url, typeof(cef_frame_t.get_url_delegate));
            }
        }

        private cef_frame_t.get_browser_delegate get_browser
        {
            get
            {
                return (cef_frame_t.get_browser_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_browser, typeof(cef_frame_t.get_browser_delegate));
            }
        }

        private cef_frame_t.visit_dom_delegate visit_dom
        {
            get
            {
                return (cef_frame_t.visit_dom_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->visit_dom, typeof(cef_frame_t.visit_dom_delegate));
            }
        }

    }
}
