//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefPostData : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefPostData proxy from pointer.
        /// </summary>
        internal static CefPostData From(cef_post_data_t* ptr)
        {
            if (ptr == null) ThrowNullNativePointer();
			return new CefPostData(ptr);
        }
		
        internal static CefPostData FromOrDefault(cef_post_data_t* ptr)
        {
            if (ptr != null) return new CefPostData(ptr);
            else return null;
        }

        private static void ThrowNullNativePointer()
        {
            throw new NullReferenceException("CefPostData");
        }

        private cef_post_data_t* ptr;

        private CefPostData(cef_post_data_t* ptr)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefPostData, this.ptr, LogOperation.Create);
#endif

            // if (addRef) this.AddRef();
        }

        #region IDisposable
        ~CefPostData()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefPostData, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_post_data_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_post_data_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_post_data_t.get_element_count_delegate get_element_count
        {
            get
            {
                return (cef_post_data_t.get_element_count_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_element_count, typeof(cef_post_data_t.get_element_count_delegate));
            }
        }

        private cef_post_data_t.get_elements_delegate get_elements
        {
            get
            {
                return (cef_post_data_t.get_elements_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_elements, typeof(cef_post_data_t.get_elements_delegate));
            }
        }

        private cef_post_data_t.remove_element_delegate remove_element
        {
            get
            {
                return (cef_post_data_t.remove_element_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->remove_element, typeof(cef_post_data_t.remove_element_delegate));
            }
        }

        private cef_post_data_t.add_element_delegate add_element
        {
            get
            {
                return (cef_post_data_t.add_element_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->add_element, typeof(cef_post_data_t.add_element_delegate));
            }
        }

        private cef_post_data_t.remove_elements_delegate remove_elements
        {
            get
            {
                return (cef_post_data_t.remove_elements_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->remove_elements, typeof(cef_post_data_t.remove_elements_delegate));
            }
        }

    }
}
