//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefResponse : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefResponse proxy from pointer.
        /// </summary>
        internal static CefResponse From(cef_response_t* ptr)
        {
			return new CefResponse(ptr, false);
        }

        /// <summary>
        /// Create CefResponse proxy from pointer and optionally increments the reference count for the object.
        /// </summary>
        internal static CefResponse Create(cef_response_t* ptr, bool addRefCount)
        {
            return new CefResponse(ptr, addRefCount);
        }

        private cef_response_t* ptr;

        private CefResponse(cef_response_t* ptr, bool addRefCount)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefResponse, this.ptr, LogOperation.Create);
#endif

			if (addRefCount) this.AddRef();
        }

        #region IDisposable
        ~CefResponse()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefResponse, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_response_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_response_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_response_t.get_status_delegate get_status
        {
            get
            {
                return (cef_response_t.get_status_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_status, typeof(cef_response_t.get_status_delegate));
            }
        }

        private cef_response_t.set_status_delegate set_status
        {
            get
            {
                return (cef_response_t.set_status_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_status, typeof(cef_response_t.set_status_delegate));
            }
        }

        private cef_response_t.get_status_text_delegate get_status_text
        {
            get
            {
                return (cef_response_t.get_status_text_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_status_text, typeof(cef_response_t.get_status_text_delegate));
            }
        }

        private cef_response_t.set_status_text_delegate set_status_text
        {
            get
            {
                return (cef_response_t.set_status_text_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_status_text, typeof(cef_response_t.set_status_text_delegate));
            }
        }

        private cef_response_t.get_mime_type_delegate get_mime_type
        {
            get
            {
                return (cef_response_t.get_mime_type_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_mime_type, typeof(cef_response_t.get_mime_type_delegate));
            }
        }

        private cef_response_t.set_mime_type_delegate set_mime_type
        {
            get
            {
                return (cef_response_t.set_mime_type_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_mime_type, typeof(cef_response_t.set_mime_type_delegate));
            }
        }

        private cef_response_t.get_header_delegate get_header
        {
            get
            {
                return (cef_response_t.get_header_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_header, typeof(cef_response_t.get_header_delegate));
            }
        }

        private cef_response_t.get_header_map_delegate get_header_map
        {
            get
            {
                return (cef_response_t.get_header_map_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_header_map, typeof(cef_response_t.get_header_map_delegate));
            }
        }

        private cef_response_t.set_header_map_delegate set_header_map
        {
            get
            {
                return (cef_response_t.set_header_map_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_header_map, typeof(cef_response_t.set_header_map_delegate));
            }
        }

    }
}
