//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefRequest : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefRequest proxy from pointer.
        /// </summary>
        internal static CefRequest From(cef_request_t* ptr)
        {
            if (ptr == null) ThrowNullNativePointer();
			return new CefRequest(ptr);
        }
		
        internal static CefRequest FromOrDefault(cef_request_t* ptr)
        {
            if (ptr != null) return new CefRequest(ptr);
            else return null;
        }

        private static void ThrowNullNativePointer()
        {
            throw new NullReferenceException("CefRequest");
        }

        private cef_request_t* ptr;

        private CefRequest(cef_request_t* ptr)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefRequest, this.ptr, LogOperation.Create);
#endif

            // if (addRef) this.AddRef();
        }

        #region IDisposable
        ~CefRequest()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefRequest, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_request_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_request_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_request_t.get_url_delegate get_url
        {
            get
            {
                return (cef_request_t.get_url_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_url, typeof(cef_request_t.get_url_delegate));
            }
        }

        private cef_request_t.set_url_delegate set_url
        {
            get
            {
                return (cef_request_t.set_url_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_url, typeof(cef_request_t.set_url_delegate));
            }
        }

        private cef_request_t.get_method_delegate get_method
        {
            get
            {
                return (cef_request_t.get_method_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_method, typeof(cef_request_t.get_method_delegate));
            }
        }

        private cef_request_t.set_method_delegate set_method
        {
            get
            {
                return (cef_request_t.set_method_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_method, typeof(cef_request_t.set_method_delegate));
            }
        }

        private cef_request_t.get_post_data_delegate get_post_data
        {
            get
            {
                return (cef_request_t.get_post_data_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_post_data, typeof(cef_request_t.get_post_data_delegate));
            }
        }

        private cef_request_t.set_post_data_delegate set_post_data
        {
            get
            {
                return (cef_request_t.set_post_data_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_post_data, typeof(cef_request_t.set_post_data_delegate));
            }
        }

        private cef_request_t.get_header_map_delegate get_header_map
        {
            get
            {
                return (cef_request_t.get_header_map_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_header_map, typeof(cef_request_t.get_header_map_delegate));
            }
        }

        private cef_request_t.set_header_map_delegate set_header_map
        {
            get
            {
                return (cef_request_t.set_header_map_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_header_map, typeof(cef_request_t.set_header_map_delegate));
            }
        }

        private cef_request_t.set_delegate set
        {
            get
            {
                return (cef_request_t.set_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set, typeof(cef_request_t.set_delegate));
            }
        }

        private cef_request_t.get_flags_delegate get_flags
        {
            get
            {
                return (cef_request_t.get_flags_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_flags, typeof(cef_request_t.get_flags_delegate));
            }
        }

        private cef_request_t.set_flags_delegate set_flags
        {
            get
            {
                return (cef_request_t.set_flags_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_flags, typeof(cef_request_t.set_flags_delegate));
            }
        }

        private cef_request_t.get_first_party_for_cookies_delegate get_first_party_for_cookies
        {
            get
            {
                return (cef_request_t.get_first_party_for_cookies_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_first_party_for_cookies, typeof(cef_request_t.get_first_party_for_cookies_delegate));
            }
        }

        private cef_request_t.set_first_party_for_cookies_delegate set_first_party_for_cookies
        {
            get
            {
                return (cef_request_t.set_first_party_for_cookies_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->set_first_party_for_cookies, typeof(cef_request_t.set_first_party_for_cookies_delegate));
            }
        }

    }
}
