//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefV8Context : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefV8Context proxy from pointer.
        /// </summary>
        internal static CefV8Context From(cef_v8context_t* ptr)
        {
            if (ptr == null) ThrowNullNativePointer();
			return new CefV8Context(ptr);
        }
		
        internal static CefV8Context FromOrDefault(cef_v8context_t* ptr)
        {
            if (ptr != null) return new CefV8Context(ptr);
            else return null;
        }

        private static void ThrowNullNativePointer()
        {
            throw new NullReferenceException("CefV8Context");
        }

        private cef_v8context_t* ptr;

        private CefV8Context(cef_v8context_t* ptr)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefV8Context, this.ptr, LogOperation.Create);
#endif

            // if (addRef) this.AddRef();
        }

        #region IDisposable
        ~CefV8Context()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefV8Context, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_v8context_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_v8context_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_v8context_t.get_browser_delegate get_browser
        {
            get
            {
                return (cef_v8context_t.get_browser_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_browser, typeof(cef_v8context_t.get_browser_delegate));
            }
        }

        private cef_v8context_t.get_frame_delegate get_frame
        {
            get
            {
                return (cef_v8context_t.get_frame_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_frame, typeof(cef_v8context_t.get_frame_delegate));
            }
        }

        private cef_v8context_t.get_global_delegate get_global
        {
            get
            {
                return (cef_v8context_t.get_global_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_global, typeof(cef_v8context_t.get_global_delegate));
            }
        }

        private cef_v8context_t.enter_delegate enter
        {
            get
            {
                return (cef_v8context_t.enter_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->enter, typeof(cef_v8context_t.enter_delegate));
            }
        }

        private cef_v8context_t.exit_delegate exit
        {
            get
            {
                return (cef_v8context_t.exit_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->exit, typeof(cef_v8context_t.exit_delegate));
            }
        }

    }
}
