//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefXmlReader : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefXmlReader proxy from pointer.
        /// </summary>
        internal static CefXmlReader FromPointer(cef_xml_reader_t* ptr)
        {
			return new CefXmlReader(ptr, false);
        }

        /// <summary>
        /// Create CefXmlReader proxy from pointer and optionally increments the reference count for the object.
        /// </summary>
        internal static CefXmlReader Create(cef_xml_reader_t* ptr, bool addRefCount)
        {
            return new CefXmlReader(ptr, addRefCount);
        }

        private cef_xml_reader_t* ptr;

        private CefXmlReader(cef_xml_reader_t* ptr, bool addRefCount)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefXmlReader, this.ptr, LogOperation.Create);
#endif

			if (addRefCount) this.AddRef();
        }

        #region IDisposable
        ~CefXmlReader()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefXmlReader, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_xml_reader_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_xml_reader_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_xml_reader_t.move_to_next_node_delegate move_to_next_node
        {
            get
            {
                return (cef_xml_reader_t.move_to_next_node_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_next_node, typeof(cef_xml_reader_t.move_to_next_node_delegate));
            }
        }

        private cef_xml_reader_t.close_delegate close
        {
            get
            {
                return (cef_xml_reader_t.close_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->close, typeof(cef_xml_reader_t.close_delegate));
            }
        }

        private cef_xml_reader_t.has_error_delegate has_error
        {
            get
            {
                return (cef_xml_reader_t.has_error_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->has_error, typeof(cef_xml_reader_t.has_error_delegate));
            }
        }

        private cef_xml_reader_t.get_error_delegate get_error
        {
            get
            {
                return (cef_xml_reader_t.get_error_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_error, typeof(cef_xml_reader_t.get_error_delegate));
            }
        }

        private cef_xml_reader_t.get_type_delegate get_type
        {
            get
            {
                return (cef_xml_reader_t.get_type_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_type, typeof(cef_xml_reader_t.get_type_delegate));
            }
        }

        private cef_xml_reader_t.get_depth_delegate get_depth
        {
            get
            {
                return (cef_xml_reader_t.get_depth_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_depth, typeof(cef_xml_reader_t.get_depth_delegate));
            }
        }

        private cef_xml_reader_t.get_local_name_delegate get_local_name
        {
            get
            {
                return (cef_xml_reader_t.get_local_name_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_local_name, typeof(cef_xml_reader_t.get_local_name_delegate));
            }
        }

        private cef_xml_reader_t.get_prefix_delegate get_prefix
        {
            get
            {
                return (cef_xml_reader_t.get_prefix_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_prefix, typeof(cef_xml_reader_t.get_prefix_delegate));
            }
        }

        private cef_xml_reader_t.get_qualified_name_delegate get_qualified_name
        {
            get
            {
                return (cef_xml_reader_t.get_qualified_name_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_qualified_name, typeof(cef_xml_reader_t.get_qualified_name_delegate));
            }
        }

        private cef_xml_reader_t.get_namespace_uri_delegate get_namespace_uri
        {
            get
            {
                return (cef_xml_reader_t.get_namespace_uri_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_namespace_uri, typeof(cef_xml_reader_t.get_namespace_uri_delegate));
            }
        }

        private cef_xml_reader_t.get_base_uri_delegate get_base_uri
        {
            get
            {
                return (cef_xml_reader_t.get_base_uri_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_base_uri, typeof(cef_xml_reader_t.get_base_uri_delegate));
            }
        }

        private cef_xml_reader_t.get_xml_lang_delegate get_xml_lang
        {
            get
            {
                return (cef_xml_reader_t.get_xml_lang_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_xml_lang, typeof(cef_xml_reader_t.get_xml_lang_delegate));
            }
        }

        private cef_xml_reader_t.is_empty_element_delegate is_empty_element
        {
            get
            {
                return (cef_xml_reader_t.is_empty_element_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->is_empty_element, typeof(cef_xml_reader_t.is_empty_element_delegate));
            }
        }

        private cef_xml_reader_t.has_value_delegate has_value
        {
            get
            {
                return (cef_xml_reader_t.has_value_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->has_value, typeof(cef_xml_reader_t.has_value_delegate));
            }
        }

        private cef_xml_reader_t.get_value_delegate get_value
        {
            get
            {
                return (cef_xml_reader_t.get_value_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_value, typeof(cef_xml_reader_t.get_value_delegate));
            }
        }

        private cef_xml_reader_t.has_attributes_delegate has_attributes
        {
            get
            {
                return (cef_xml_reader_t.has_attributes_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->has_attributes, typeof(cef_xml_reader_t.has_attributes_delegate));
            }
        }

        private cef_xml_reader_t.get_attribute_count_delegate get_attribute_count
        {
            get
            {
                return (cef_xml_reader_t.get_attribute_count_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_attribute_count, typeof(cef_xml_reader_t.get_attribute_count_delegate));
            }
        }

        private cef_xml_reader_t.get_attribute_byindex_delegate get_attribute_byindex
        {
            get
            {
                return (cef_xml_reader_t.get_attribute_byindex_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_attribute_byindex, typeof(cef_xml_reader_t.get_attribute_byindex_delegate));
            }
        }

        private cef_xml_reader_t.get_attribute_byqname_delegate get_attribute_byqname
        {
            get
            {
                return (cef_xml_reader_t.get_attribute_byqname_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_attribute_byqname, typeof(cef_xml_reader_t.get_attribute_byqname_delegate));
            }
        }

        private cef_xml_reader_t.get_attribute_bylname_delegate get_attribute_bylname
        {
            get
            {
                return (cef_xml_reader_t.get_attribute_bylname_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_attribute_bylname, typeof(cef_xml_reader_t.get_attribute_bylname_delegate));
            }
        }

        private cef_xml_reader_t.get_inner_xml_delegate get_inner_xml
        {
            get
            {
                return (cef_xml_reader_t.get_inner_xml_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_inner_xml, typeof(cef_xml_reader_t.get_inner_xml_delegate));
            }
        }

        private cef_xml_reader_t.get_outer_xml_delegate get_outer_xml
        {
            get
            {
                return (cef_xml_reader_t.get_outer_xml_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_outer_xml, typeof(cef_xml_reader_t.get_outer_xml_delegate));
            }
        }

        private cef_xml_reader_t.get_line_number_delegate get_line_number
        {
            get
            {
                return (cef_xml_reader_t.get_line_number_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_line_number, typeof(cef_xml_reader_t.get_line_number_delegate));
            }
        }

        private cef_xml_reader_t.move_to_attribute_byindex_delegate move_to_attribute_byindex
        {
            get
            {
                return (cef_xml_reader_t.move_to_attribute_byindex_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_attribute_byindex, typeof(cef_xml_reader_t.move_to_attribute_byindex_delegate));
            }
        }

        private cef_xml_reader_t.move_to_attribute_byqname_delegate move_to_attribute_byqname
        {
            get
            {
                return (cef_xml_reader_t.move_to_attribute_byqname_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_attribute_byqname, typeof(cef_xml_reader_t.move_to_attribute_byqname_delegate));
            }
        }

        private cef_xml_reader_t.move_to_attribute_bylname_delegate move_to_attribute_bylname
        {
            get
            {
                return (cef_xml_reader_t.move_to_attribute_bylname_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_attribute_bylname, typeof(cef_xml_reader_t.move_to_attribute_bylname_delegate));
            }
        }

        private cef_xml_reader_t.move_to_first_attribute_delegate move_to_first_attribute
        {
            get
            {
                return (cef_xml_reader_t.move_to_first_attribute_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_first_attribute, typeof(cef_xml_reader_t.move_to_first_attribute_delegate));
            }
        }

        private cef_xml_reader_t.move_to_next_attribute_delegate move_to_next_attribute
        {
            get
            {
                return (cef_xml_reader_t.move_to_next_attribute_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_next_attribute, typeof(cef_xml_reader_t.move_to_next_attribute_delegate));
            }
        }

        private cef_xml_reader_t.move_to_carrying_element_delegate move_to_carrying_element
        {
            get
            {
                return (cef_xml_reader_t.move_to_carrying_element_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_carrying_element, typeof(cef_xml_reader_t.move_to_carrying_element_delegate));
            }
        }

    }
}
