//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace CefGlue
{
    using System;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Threading;
    using Core;
	using Diagnostics;

    public sealed unsafe partial class CefZipReader : IDisposable
	{
#if DIAGNOSTICS
		internal static int ObjectCt;
#endif

        /// <summary>
        /// Create CefZipReader proxy from pointer.
        /// </summary>
        internal static CefZipReader From(cef_zip_reader_t* ptr)
        {
            if (ptr == null) ThrowNullNativePointer();
			return new CefZipReader(ptr);
        }
		
        internal static CefZipReader FromOrDefault(cef_zip_reader_t* ptr)
        {
            if (ptr != null) return new CefZipReader(ptr);
            else return null;
        }

        private static void ThrowNullNativePointer()
        {
            throw new NullReferenceException("CefZipReader");
        }

        private cef_zip_reader_t* ptr;

        private CefZipReader(cef_zip_reader_t* ptr)
        {
            this.ptr = ptr;

#if DIAGNOSTICS
            Interlocked.Increment(ref ObjectCt);
            Cef.Logger.Trace(LogTarget.CefZipReader, this.ptr, LogOperation.Create);
#endif

            // if (addRef) this.AddRef();
        }

        #region IDisposable
        ~CefZipReader()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (this.ptr != null)
            {
                var refct = ReleaseRef();
#if DIAGNOSTICS
                var total = Interlocked.Decrement(ref ObjectCt);
                Cef.Logger.Trace(LogTarget.CefZipReader, this.ptr, LogOperation.Dispose, "RefCount=[{0}]", refct);
#endif
                this.ptr = null;
            }
        }
        #endregion

        private cef_base_t.add_ref_delegate add_ref
        {
            get
            {
                return (cef_base_t.add_ref_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.add_ref, typeof(cef_base_t.add_ref_delegate));
            }
        }

        private cef_base_t.release_delegate release
        {
            get
            {
                return (cef_base_t.release_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.release, typeof(cef_base_t.release_delegate));
            }
        }

        private cef_base_t.get_refct_delegate get_refct
        {
            get
            {
                return (cef_base_t.get_refct_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->@base.get_refct, typeof(cef_base_t.get_refct_delegate));
            }
        }

        /// <summary>
        /// The AddRef method increments the reference count for the object. It should
        /// be called for every new copy of a pointer to a given object. The resulting
        /// reference count value is returned and should be used for diagnostic/testing
        /// purposes only.
        /// </summary>
        internal int AddRef()
        {
            return add_ref(&this.ptr->@base);
        }

        /// <summary>
        /// The Release method decrements the reference count for the object. If the
        /// reference count on the object falls to 0, then the object should free
        /// itself from memory.  The resulting reference count value is returned and
        /// should be used for diagnostic/testing purposes only.
        /// </summary>
        internal int ReleaseRef()
        {
            return release(&this.ptr->@base);
        }

        /// <summary>
        /// Return the current number of references.
        /// </summary>
        internal int RefCount
        {
            get { return get_refct(&this.ptr->@base); }
        }

        internal cef_zip_reader_t* NativePointer
        {
            get
            {
                return this.ptr;
            }
        }

        internal cef_zip_reader_t* GetNativePointerAndAddRef()
        {
            AddRef();
            return this.ptr;
        }

        private cef_zip_reader_t.move_to_first_file_delegate move_to_first_file
        {
            get
            {
                return (cef_zip_reader_t.move_to_first_file_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_first_file, typeof(cef_zip_reader_t.move_to_first_file_delegate));
            }
        }

        private cef_zip_reader_t.move_to_next_file_delegate move_to_next_file
        {
            get
            {
                return (cef_zip_reader_t.move_to_next_file_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_next_file, typeof(cef_zip_reader_t.move_to_next_file_delegate));
            }
        }

        private cef_zip_reader_t.move_to_file_delegate move_to_file
        {
            get
            {
                return (cef_zip_reader_t.move_to_file_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->move_to_file, typeof(cef_zip_reader_t.move_to_file_delegate));
            }
        }

        private cef_zip_reader_t.close_delegate close
        {
            get
            {
                return (cef_zip_reader_t.close_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->close, typeof(cef_zip_reader_t.close_delegate));
            }
        }

        private cef_zip_reader_t.get_file_name_delegate get_file_name
        {
            get
            {
                return (cef_zip_reader_t.get_file_name_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_file_name, typeof(cef_zip_reader_t.get_file_name_delegate));
            }
        }

        private cef_zip_reader_t.get_file_size_delegate get_file_size
        {
            get
            {
                return (cef_zip_reader_t.get_file_size_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_file_size, typeof(cef_zip_reader_t.get_file_size_delegate));
            }
        }

        private cef_zip_reader_t.get_file_last_modified_delegate get_file_last_modified
        {
            get
            {
                return (cef_zip_reader_t.get_file_last_modified_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->get_file_last_modified, typeof(cef_zip_reader_t.get_file_last_modified_delegate));
            }
        }

        private cef_zip_reader_t.open_file_delegate open_file
        {
            get
            {
                return (cef_zip_reader_t.open_file_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->open_file, typeof(cef_zip_reader_t.open_file_delegate));
            }
        }

        private cef_zip_reader_t.close_file_delegate close_file
        {
            get
            {
                return (cef_zip_reader_t.close_file_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->close_file, typeof(cef_zip_reader_t.close_file_delegate));
            }
        }

        private cef_zip_reader_t.read_file_delegate read_file
        {
            get
            {
                return (cef_zip_reader_t.read_file_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->read_file, typeof(cef_zip_reader_t.read_file_delegate));
            }
        }

        private cef_zip_reader_t.tell_delegate tell
        {
            get
            {
                return (cef_zip_reader_t.tell_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->tell, typeof(cef_zip_reader_t.tell_delegate));
            }
        }

        private cef_zip_reader_t.eof_delegate eof
        {
            get
            {
                return (cef_zip_reader_t.eof_delegate)Marshal.GetDelegateForFunctionPointer(this.ptr->eof, typeof(cef_zip_reader_t.eof_delegate));
            }
        }

    }
}
